version: '3.8'

services:
  # React Component Executor (Lightweight Docker)
  react-executor:
    build:
      context: ./react-executor
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./react-executor/components:/app/components
      - ./react-executor/public:/app/public
    environment:
      - NODE_ENV=production
    networks:
      - codeact-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Main Next.js ChatBot Interface (Development)
  codeact-chat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - REACT_EXECUTOR_URL=http://react-executor:4000
    env_file:
      - .env
    depends_on:
      - react-executor
    networks:
      - codeact-network
    profiles:
      - development

networks:
  codeact-network:
    driver: bridge

volumes:
  react_components:
  react_screenshots:
