version: '3.8'

services:
  # Development React CodeAct Learning Bot
  codeact-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Hot reload for development
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - codeact-network

  # Production React CodeAct Learning Bot
  codeact-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - codeact-network
    profiles:
      - production

networks:
  codeact-network:
    driver: bridge

volumes:
  node_modules:
  next_cache:
